name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup credentails
        env: # Or as an environment variable
          HIN_CLIENT_ID: ${{ secrets.HIN_CLIENT_ID }}
          HIN_CLIENT_SECRET: ${{ secrets.HIN_CLIENT_SECRET }}
        run: |
          sed -i "s/YOUR_HIN_CLIENT_ID/$HIN_CLIENT_ID/;s/YOUR_HIN_CLIENT_SECRET/$HIN_CLIENT_SECRET/;s/YOUR_CERTIFACTION_SERVER/$CERTIFACTION_SERVER/" ./app/controllers/OAuthController.java
      - run: |
          ./bin/activator dist

      - name: Upload server jar
        uses: actions/upload-artifact@v4
        with:
          name: server-jar
          retention-days: 7
          path: target/universal/amikoweb-1.0-SNAPSHOT.zip
