name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - run: |
          ./bin/activator dist

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            target/universal/amikoweb-1.0-SNAPSHOT.zip
