name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup credentails
        env: # Or as an environment variable
          HIN_CLIENT_ID: ${{ secrets.HIN_CLIENT_ID }}
          HIN_CLIENT_SECRET: ${{ secrets.HIN_CLIENT_SECRET }}
          CERTIFACTION_SERVER: ${{ secrets.CERTIFACTION_SERVER }}
          CERTIFACTION_TEST_SERVER: ${{ secrets.CERTIFACTION_TEST_SERVER }}
        run: |
          sed -i "s/YOUR_HIN_CLIENT_ID/$HIN_CLIENT_ID/;s/YOUR_HIN_CLIENT_SECRET/$HIN_CLIENT_SECRET/;s/YOUR_CERTIFACTION_SERVER/$CERTIFACTION_SERVER/;s/YOUR_CERTIFACTION_TEST_SERVER/$CERTIFACTION_TEST_SERVER/" ./app/controllers/OAuthController.java
      - run: |
          ./bin/activator dist

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            target/universal/amikoweb-1.0-SNAPSHOT.zip
